# Generated by Django 5.0.4 on 2024-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ball_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
